#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"
opt = OptionParser.new
opt.on("-t", "--to PATH", "output path") { |v| @to = v }
opt.on("-d", "--dsl PATH", "dsl path") { |v| @dsl = v }
opt.on("-h", "--help", "show this help") do
  puts opt
  exit
end

opt.parse!(ARGV)
@froms = ARGV

require "classifile"
exe = Classifile::Execute.new
exe.test @dsl, @froms, @to
